name = "Chipewyan"
version = "0.1.1"

# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Chipewyan spellchecker"
chp = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Chipewyan, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
chp = "TRANSLATE: A spellchecker for Chipewyan, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.chp"

[windows]
system_product_code = "{103E96D0-4F2E-40F6-A0E4-71F9FD072DCB}_is1"
legacy_product_codes = [
    { value = "EB54BC67-A5C1-4BB7-A3F5-1B38DBE83DB3", kind = "nsis" },
    { value = "2248549B-9EF4-44B1-ABA7-6B9CF4C5A769", kind = "nsis" }
]
