name = "Chipewyan"
version = "0.1.1"

[macos]
system_pkg_id = "no.divvun.MacDivvun.chp"

[windows]
system_product_code = "{103E96D0-4F2E-40F6-A0E4-71F9FD072DCB}_is1"
legacy_product_codes = [
    { value = "EB54BC67-A5C1-4BB7-A3F5-1B38DBE83DB3", kind = "nsis" },
    { value = "2248549B-9EF4-44B1-ABA7-6B9CF4C5A769", kind = "nsis" }
]
