[package]
name = "chp"
human_name = "Chipewyan"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.chp]
filename = "chp-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-chp"
platform = "windows"
uuid = "EB54BC67-A5C1-4BB7-A3F5-1B38DBE83DB3"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.chp"
package = "speller-chp"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-chp-mso"
platform = "windows"
uuid = "2248549B-9EF4-44B1-ABA7-6B9CF4C5A769"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-chp"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
